name: courieronedelivery
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  grouped_buttons: ^1.0.4
  google_fonts: ^1.1.0
  flutter_phoenix: ^0.1.0
  country_code_picker: ^1.3.15
  #libphonenumber: 1.0.2
  flutter_bloc: ^6.1.0
  equatable: ^1.2.0
  toast: ^0.1.5
  google_sign_in: ^4.5.1
  http: ^0.12.1
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.7+3
  geolocator: ^6.0.0+3
  flutter_polyline_points: ^0.2.1
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1
  onesignal_flutter: ^2.6.3
  uuid: ^2.2.2
  fluttertoast: ^7.1.8
  image_picker: 0.6.7+22
  google_maps_flutter: ^0.5.28+1
  map_launcher: ^1.1.3+1
  flutter_google_places: ^0.2.5
  geocoding: ^1.0.5
  url_launcher: ^5.7.10
  confirm_dialog: ^1.0.0
  simple_moment: ^1.1.0
  focus_detector: ^2.0.0
  share: ^2.0.1
  progress_dialog: ^1.2.4
  cached_network_image: 2.5.1

  #firebase
  firebase_core: ^0.6.0
  firebase_analytics: ^7.0.0
  firebase_auth: ^0.19.0+1
  firebase_storage: ^6.0.0
  firebase_database: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.5.0
  retrofit_generator: ^1.4.1+1
  flutter_launcher_icons: "^0.8.1"
  flutter_launcher_name: "^0.0.1"
  flutter_native_splash: "0.3.1"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  image: "assets/app_splash.png"
  color: "#FDB817"

flutter_launcher_name:
  name: "CourierOne Delivery"

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Bold.ttf
        - asset: fonts/ProductSans-Regular.ttf
